### ISSUE TITLE
Fewer passwords, more security! 

### ISSUE THREAD

**Issue by hemebond** [dagnelies/passwordless-www#5]
At the top of the homepage is the phrase:

>  Less passwords, more security! 

But it should say:

>  Fewer passwords, more security! 

A tiny nitpick, but it was the first thing I saw when I visited the page :-P

**Comment by dagnelies** [comment]
Thanks for pointing that out. I guess my unix geekiness with "less is more" kicked in... But somehow I'm not a fan of the new sentence "Fewer passwords, more security!". Since the first one is not proper English, perhaps I should change it completely.
*Thinking aloud...* Perhaps "Get rid of passwords, increase security!" or "No more passwords, better security!" ...I'll sleep over it.

**Comment by dagnelies** [comment]
Changed to "Get rid of passwords, boost security!"

**Comment by dagnelies** [comment]
Rechanging to "Dump passwords, boost security!"
