### ISSUE TITLE
Error when trying from openidconnect.net

### ISSUE THREAD

**Issue by anderspitman** [dagnelies/passwordless-www#9]
Auth0 has a nice OAuth2 login testing tool at https://openidconnect.net/. I tried it with `api.passwordless.id` and it didn't work. I also ran into an error with a self-hosted application.

As a side question, is the code for the backend open source?

**Comment by dagnelies** [comment]
😮 Oh, that's good you noticed!

I wonder what the issue is. On the top of my head, the only thing that comes to mind is that the issued id token has no `kid` (Public Key ID). Usually, most implementation then pick the first one available in the [published keys](https://[api.passwordless.id/openid/jwks](https://api.passwordless.id/openid/jwks)) by default ...perhaps they do not ...I wonder. Their error is extremely vague too. I'll investigate what's going on.

> I also ran into an error with a self-hosted application.

What error did you encounter exactly?

> As a side question, is the code for the backend open source?

Currently neither backend nor frontend is open source. I hesitated quite a lot regarding this aspect, and still do. In the end, I chose against for following reasons:

- *Avoiding clones*: the strength of Passwordless.ID relies on being a centralized identity provider, so that users register and manage their devices in a single place, same for their profile. Making it open source would likely result in similar copycats, and would defy this purpose.
- *Security*: this is a double-edged sword. On one hand, being open source allows third parties to scrutinize the correctness of the code. On the other hand, attackers are notified on the fly when dependency vulnerabilities are discovered, allowing opportunities until the patch goes through.
- *Future sustainability*: while authentication and security are meant to be kept free for everyone, I was envisioning the possibility to add additional "premium" features in the future like analytics, access control, address verification and other stuff in the future.

But the main reason is indeed avoiding "the competition of clones". It's like GitHub. It ain't open source either and I believe that if it was, it would have likely lead to a more fragmented community than otherwise.

That said, I'm considering the possibility of open sourcing this. It started as a little pet project but it's a bottomless pit. However, I would prefer to open source once it picked up enough steam and community to ensure a long lived presence and avoid fragmentation due to forks.

**Comment by anderspitman** [comment]
I believe the problem I ran into with my client was withing the missing kid as well. Is there a reason your JWKS doesn't include kids?

Thanks for the detailed response.

**Comment by dagnelies** [comment]
No particular reason, it was just because the underlying lib did not produce them by default and because the tools I used for JWT also worked just fine without.

**Comment by anderspitman** [comment]
Fair enough

**Comment by dagnelies** [comment]
Well, it's late but I can confirm it's because of the missing `kid` in the token header. Now that the helper lib added that, I'll fix it soon too.

**Comment by dagnelies** [comment]
Fixed. PS: it had nothing to do with the helper lib but a missing env variable in prod.
